// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwv98CfLvt4Tj5QCqGIE_I0YKM1tN4xdo',
    appId: '1:827078049185:web:1e35ff5e764cc44aab9fe0',
    messagingSenderId: '827078049185',
    projectId: 'reading-tutor-f680c',
    authDomain: 'reading-tutor-f680c.firebaseapp.com',
    storageBucket: 'reading-tutor-f680c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnrVsZJEcZIpeJhW4Cbh05BcVDXzBacQg',
    appId: '1:827078049185:android:7b0b3758e3341f5cab9fe0',
    messagingSenderId: '827078049185',
    projectId: 'reading-tutor-f680c',
    storageBucket: 'reading-tutor-f680c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8OgjpxczGCW3Zvnw2mSxQeSs0aiGxM3k',
    appId: '1:827078049185:ios:7085ce096a546b65ab9fe0',
    messagingSenderId: '827078049185',
    projectId: 'reading-tutor-f680c',
    storageBucket: 'reading-tutor-f680c.firebasestorage.app',
    iosClientId: '827078049185-vrnme09rfdjfgd7aoi0g5moltir6fosm.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );
}
